name: Website Deployment

on: [push]

env:
  location: eastus
  appName: familywebsite
  environ: dev
  domainName: 'thehodgesfamily.net'
  indexDocument: 'index.html'
  errorDocument404Path: 'error.html'
  DnsZone: '/subscriptions/2f9cc458-4951-43a4-8231-a7b3c75b5473/resourceGroups/Core_Services/providers/Microsoft.Network/dnszones/thehodgesfamily.net'

jobs:
  create-rg:
    runs-on: ubuntu-latest
    outputs:
      rgName: ${{ steps.rg.outputs.rgName }}
      actualAppName: ${{steps.rg.outputs.actualAppName}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      
      - name: Create rg
        id: rg
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.location }}
          template: ./create_rg.json
          parameters: appName=${{env.appName}} environment=${{env.environ}} location=${{env.location}}

  create-storage:
    runs-on: ubuntu-latest
    needs: create-rg
    outputs:
      storageName: ${{steps.storage.outputs.storageName}}
      storageWebEndpoint: ${{steps.storage.outputs.storageWebEndpoint}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'

      - name: Create Storage
        uses: azure/arm-deploy@v2
        id: storage
        with:
          scope: resourcegroup
          resourceGroupName: ${{ needs.create-rg.outputs.rgName }}
          template: ./create_storage.json
          parameters: appName=${{env.appName}} environment=${{env.environ}}

  create-afd:
    runs-on: ubuntu-latest
    needs: [create-rg,create-storage]
    outputs:
      profileName: ${{steps.afd.outputs.profileName}}
      customDomainName: ${{steps.afd.outputs.customDomainName}}
      endpointName: ${{steps.afd.outputs.endpointName}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'

      - name: Create Frontdoor
        uses: azure/arm-deploy@v2
        id: afd
        with:
          scope: resourcegroup
          resourceGroupName: ${{needs.create-rg.outputs.rgName}}
          template: ./create_afd.json
          parameters: appName=${{env.appName}} environment=${{env.environ}} DnsZone=${{env.DnsZone}} domainName=${{env.domainName}} storageWebEndpoint=${{needs.create-storage.outputs.storageWebEndpoint}}

  create-db:
    runs-on: ubuntu-latest
    needs: create-rg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Create DB
        uses: azure/arm-deploy@v2
        id: db
        with:
          scope: resourcegroup
          resourceGroupName: ${{needs.create-rg.outputs.rgName}}
          template: ./create_db.json
          parameters: appName=${{env.appName}} environment=${{env.environ}}

  enable-staticweb:
    runs-on: ubuntu-latest
    needs: [create-rg,create-storage,create-afd]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Enable Static Web
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $ErrorActionPreference = 'Stop'
            $storageAccount = Get-AzStorageAccount -ResourceGroupName ${{needs.create-rg.outputs.rgName}} -AccountName ${{needs.create-storage.outputs.storageName}}
            $ctx = $storageAccount.Context
            Enable-AzStorageStaticWebsite -Context $ctx -IndexDocument $env:indexDocument -ErrorDocument404Path $env:errorDocument404Path
            $customDomainHttpsParameter = New-AzCdnManagedHttpsParametersObject -CertificateSourceParameterCertificateType Dedicated -CertificateSource Cdn -ProtocolType ServerNameIndication
            Enable-AzCdnCustomDomainCustomHttps -ResourceGroupName ${{needs.create-rg.outputs.rgName}} -ProfileName ${{needs.create-afd.outputs.profileName}} -EndpointName ${{needs.create-storage.outputs.storageWebEndpoint}} -CustomDomainName ${{needs.create-afd.outputs.customDomainName}} -CustomDomainHttpsParameter $customDomainHttpsParameter
          azPSVersion: "latest"

  deploy-dns:
    runs-on: ubuntu-latest
    needs: [create-rg,create-afd]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Deploy DNS
        uses: azure/powershell@v2
        id: dns
        with:
          
          inlineScript: |
            $ErrorActionPreference = 'Stop'
            Set-AzContext -Subscription "2f9cc458-4951-43a4-8231-a7b3c75b5473"
            $rs = Get-AzDnsRecordSet -Name ${{env.environ}} -RecordType CNAME -ZoneName ${{env.domainName}} -ResourceGroupName "core_services"
            Remove-AzDnsRecordConfig -RecordSet $rs -Cname $rs.Records.cname | Set-AzDnsRecordSet
            $newcname = '${{needs.create-afd.outputs.endpointName}}'
            Get-AzDnsRecordSet -name ${{env.environ}} -RecordType CNAME -ZoneName ${{env.domainName}} -ResourceGroupName "core_services" | Add-AzDnsRecordConfig -Cname $newcname | Set-AzDnsRecordSet
          azPSVersion: "latest"

  create-app:
    runs-on: ubuntu-latest
    needs: [create-rg,create-storage]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login with Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Create App Service Plan
        uses: azure/arm-deploy@v2
        id: ASP
        with:
          scope: resourcegroup
          resourceGroupName: ${{needs.create-rg.outputs.rgName}}
          template: ./create_app.json
          parameters: environment=${{env.environ}}

      - name: Deploy App
        uses: azure/powershell@v2
        with: 
          inlineScript: |
            $ErrorActionPreference = 'Continue'
            $storageAccount = Get-AzStorageAccount -ResourceGroupName ${{needs.create-rg.outputs.rgName}} -AccountName ${{needs.create-storage.outputs.storageName}}
            $ctx = $storageAccount.Context
            $ContainerName = 'app'
            New-AzStorageContainer -Name $ContainerName -Context $Ctx
            Set-AzStorageBlobContent -File 'd:\cloud\api\visit_trigger.zip' -Container $ContainerName -Context $ctx
          azPSVersion: "latest"