name: Website Deployment

on: [push]

env:
  location: eastus

jobs:
  create-rg:
    runs-on: ubuntu-latest
    outputs:
      rgName: ${{ steps.rg.outputs.rgName }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      
      - name: Create rg
        id: rg
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: ${{ env.location }}
          template: ./create_rg.json
          parameters: ./create_rg.parameters.json

      

  create-storage:
    runs-on: ubuntu-latest
    needs: create-rg
    steps:
      
      - name: Create Storage
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ needs.create-rg.outputs.rgName }}
          template: ./create_storage.json
          parameters: ./create_rg.parameters.json