name: Website Deployment

on: [push]

env:
  location: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true

      
      
      - name: Create rg
        uses: azure/powershell@v1
        with:
          azPSVersion: 3.1.0,
          inlineScript: |
            New-AzResourceGroup -Name 'website-rg' -Location ${{ env.location }}